language: python
python:
- '2.7'
- '3.6'
before_install:
  - pip install --upgrade pip
install:
  - pip install -r tools/requirements.txt
script:
  - python tools/util/google_fonts.py --nam_dir=tools/encodings
  - python tools/util/filter_lists.py tools/encodings/GF\ Glyph\ Sets/
